# Generated by Django 6.0.1 on 2026-01-17 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GROCERIES', 'Groceries'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('BOOKS', 'Books'), ('OTHER', 'Other'), ('RIDE', 'Ride / Transport'), ('TUTORING', 'Tutoring'), ('BEAUTY', 'Hair & Beauty'), ('TECH_SUPPORT', 'Tech Support'), ('LABOR', 'Manual Labor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='MarketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
